apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: observability
type: Opaque
stringData:
  POSTGRES_USER: observability
  POSTGRES_PASSWORD: observability
  JWT_SECRET: change-me-to-a-very-long-256-bit-secret-key
