apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  JWT_SECRET: {{ .Values.jwtSecret | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: {{ .Values.namespace }}
data:
  EUREKA_SERVER_URL: http://service-registry:8761/eureka/
  CONFIG_SERVER_URL: http://config-server:8888
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}
  POSTGRES_PORT: "5432"
  ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
  PROMETHEUS_URL: http://prometheus:9090
  NOTIFICATION_SERVICE_URL: http://notification-service:8084
